name = "gentechmediasolutions"
pages_build_output_dir = "dist"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gentech-db"
database_id = "e5354c81-36ef-4f8c-b48f-c4fe90cf17e6"
